### ISSUE TITLE
error in mongodb connection and in unirest

### ISSUE THREAD

**Issue by amirensit** [zarinlo/sample-springboot-api#1]
Hello.
I downloaded the final project from github and I get these following errors:

**1. Unable to connect to mongodb:**

```
com.mongodb.MongoSocketOpenException: Exception opening socket
	at com.mongodb.connection.SocketStream.open(SocketStream.java:62) ~[mongodb-driver-core-3.6.4.jar:na]
	at com.mongodb.connection.InternalStreamConnection.open(InternalStreamConnection.java:126) ~[mongodb-driver-core-3.6.4.jar:na]
	at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:114) ~[mongodb-driver-core-3.6.4.jar:na]
	at java.base/java.lang.Thread.run(Thread.java:835) ~[na:na]
Caused by: java.net.ConnectException: Connection refused: connect
	at java.base/java.net.PlainSocketImpl.waitForConnect(Native Method) ~[na:na]
	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:107) ~[na:na]
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399) ~[na:na]
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242) ~[na:na]
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224) ~[na:na]
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403) ~[na:na]
	at java.base/java.net.Socket.connect(Socket.java:591) ~[na:na]
	at com.mongodb.connection.SocketStreamHelper.initialize(SocketStreamHelper.java:59) ~[mongodb-driver-core-3.6.4.jar:na]
	at com.mongodb.connection.SocketStream.open(SocketStream.java:57) ~[mongodb-driver-core-3.6.4.jar:na]
	... 3 common frames omitted
```
I solved this by either 

- running an embedded mongodb  (maven dependency): 

```
<dependency>
            <groupId>de.flapdoodle.embed</groupId>
            <artifactId>de.flapdoodle.embed.mongo</artifactId>
            <version>2.2.0</version>
</dependency>
```

- Or by running a docker mongo image:
```
docker run mongo
```

**2. JSONException with unirest:**

```
om.mashape.unirest.http.exceptions.UnirestException: java.lang.RuntimeException: java.lang.RuntimeException: org.json.JSONException: A JSONArray text must start with '[' at 1 [character 2 line 1]
```
Here either the response is null or It does not start with '[' and I suggest to create a file and use inirest to get data from that file like mentioned [here ](https://stackoverflow.com/a/27517723/6717287).

**Comment by zarinlo** [comment]
@amirensit Apologies in the delay! A local instance of mongodb is required to run this sample, but thank you for providing a workaround with the embedded mongodb maven dependency. I will make a note once I update this repo.

**Comment by zarinlo** [comment]
@amirensit FYI: Updated the project and included the embedded mongo dependency as a note in the README as well as the tutorial found here: https://zarin.io/codelabs/springboot-api 

Thanks again!
